<a href="https://colab.research.google.com/github/Naman09746/ML-practise/blob/main/numpy_practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a 1D NumPy array
array_1d = np.arange(1, 10)
print("1D Array:", array_1d)

1D Array: [1 2 3 4 5 6 7 8 9]


In [11]:
# Retrieve the 4th element of the array (index 3)
fourth_element = array_1d[3]
print("4th Element:", fourth_element)

# Retrieve the last element of the array
last_element = array_1d[-1]
print("Last Element:", last_element)

4th Element: 4
Last Element: 9


In [12]:
# Slice the array to get the first 4 elements
first_5_elements = array_1d[:5]
print("First 5 Elements:", first_5_elements)

# Slice the array to get every other element
every_other_element = array_1d[::2]
print("Every Other Element:", every_other_element)

# Slice the array to get the last 5 elements
last_5_elements = array_1d[-5:]
print("Last 5 Elements:", last_5_elements)

First 5 Elements: [1 2 3 4 5]
Every Other Element: [1 3 5 7 9]
Last 5 Elements: [5 6 7 8 9]


# **Excercise-2**

In [8]:
# Create a 2D NumPy array
array_2d = np.arange(1, 17).reshape(4, 4)
print("2D Array:\n", array_2d)

2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [14]:
# Retrieve the element at row 2, column 3 (indexing starts from 0)
element_2d = array_2d[1, 2]
print("Element at (2, 3):", element_2d)

# Retrieve the last element of the array
last_element_2d = array_2d[-1, -1]
print("Last Element:", last_element_2d)

Element at (2, 3): 7
Last Element: 16


In [15]:
# Slice the array to get the first two rows
first_two_rows = array_2d[:2, :]
print("First Two Rows:\n", first_two_rows)

# Slice the array to get the last two columns
last_two_columns = array_2d[:, -2:]
print("Last Two Columns:\n", last_two_columns)

# Slice the array to get the sub-array from row 2 to 4 and column 1 to 3
sub_array_2d = array_2d[1:4, 1:4]
print("Sub-array from (2:5, 2:4):\n", sub_array_2d)


First Two Rows:
 [[1 2 3 4]
 [5 6 7 8]]
Last Two Columns:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
Sub-array from (2:5, 2:4):
 [[ 6  7  8]
 [10 11 12]
 [14 15 16]]


# **Exercise 3: 3D Arrays**

In [16]:
# Create a 3D NumPy array
array_3d = np.arange(1, 28).reshape(3, 3, 3)
print("3D Array:\n", array_3d)


3D Array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [17]:
# Retrieve the element at index (1, 1, 1)
element_3d = array_3d[1, 1, 1]
print("Element at (1, 1, 1):", element_3d)

# Retrieve the last element of the array
last_element_3d = array_3d[-1, -1, -1]
print("Last Element:", last_element_3d)


Element at (1, 1, 1): 14
Last Element: 27


In [18]:
# Slice the array to get the first two 2D arrays
first_two_2d_arrays = array_3d[:2, :, :]
print("First Two 2D Arrays:\n", first_two_2d_arrays)

# Slice the array to get the last 2 elements of the last 2D array
last_two_elements_last_2d = array_3d[-1, -2:, :]
print("Last 2 Elements of Last 2D Array:\n", last_two_elements_last_2d)

# Slice the array to get a sub-array of shape (2, 2, 2) from the original array
sub_array_3d = array_3d[:2, :2, :2]
print("Sub-array (2, 2, 2):\n", sub_array_3d)


First Two 2D Arrays:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
Last 2 Elements of Last 2D Array:
 [[22 23 24]
 [25 26 27]]
Sub-array (2, 2, 2):
 [[[ 1  2]
  [ 4  5]]

 [[10 11]
  [13 14]]]


# **Additional Exercises**

In [19]:
# Create a 1D NumPy array of the first 15 positive integers
array_1d_extra = np.arange(1, 16)

# Use boolean indexing to retrieve all elements that are multiples of 3
multiples_of_3 = array_1d_extra[array_1d_extra % 3 == 0]
print("Multiples of 3:", multiples_of_3)


Multiples of 3: [ 3  6  9 12 15]


In [20]:
# Create a 2D NumPy array of shape (4, 5) with values from 1 to 20
array_2d_extra = np.arange(1, 21).reshape(4, 5)

# Retrieve the first column
first_column = array_2d_extra[:, 0]
print("First Column:", first_column)

# Retrieve the first row and last column
first_row_last_column = array_2d_extra[0, -1]
print("First Row, Last Column:", first_row_last_column)

# Retrieve the sub-array consisting of the first two rows and the last three columns
sub_array_2d_extra = array_2d_extra[:2, -3:]
print("Sub-array (First 2 Rows, Last 3 Columns):\n", sub_array_2d_extra)


First Column: [ 1  6 11 16]
First Row, Last Column: 5
Sub-array (First 2 Rows, Last 3 Columns):
 [[ 3  4  5]
 [ 8  9 10]]


# **Additional Challenges**

In [22]:
# Create a 1D array of 27 elements
array_1d_challenge = np.arange(1, 28)

# Reshape it into a 3D array of shape (3, 3, 3)
array_3d_challenge = array_1d_challenge.reshape(3, 3, 3)

# Slice to retrieve the first 2D array
first_2d_array = array_3d_challenge[0]
print("First 2D Array:\n", first_2d_array)

# Slice to retrieve the last row of the last 2D array
last_row_last_2d = array_3d_challenge[-1, -1, :]
print("Last Row of the Last 2D Array:", last_row_last_2d)


First 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Last Row of the Last 2D Array: [25 26 27]


In [21]:
# Create a 2D array of shape (6, 6) with values from 1 to 36
array_2d_challenge = np.arange(1, 37).reshape(6, 6)

# Use boolean indexing to replace all even numbers with -1
array_2d_challenge[array_2d_challenge % 2 == 0] = -1
print("Array with Even Numbers Replaced:\n", array_2d_challenge)


Array with Even Numbers Replaced:
 [[ 1 -1  3 -1  5 -1]
 [ 7 -1  9 -1 11 -1]
 [13 -1 15 -1 17 -1]
 [19 -1 21 -1 23 -1]
 [25 -1 27 -1 29 -1]
 [31 -1 33 -1 35 -1]]


In [23]:
# Create a 2D array of shape (5, 5) with random integers between 10 and 50
array_2d_random = np.random.randint(10, 51, size=(5, 5))
print("Original 2D Array:\n", array_2d_random)

# Slice to get a sub-array of shape (3, 3) from the center
center_sub_array = array_2d_random[1:4, 1:4]
print("Center Sub-array (3, 3):\n", center_sub_array)

# Subtract 10 from each element of this sub-array
center_sub_array -= 10
print("Modified Sub-array (3, 3):\n", center_sub_array)


Original 2D Array:
 [[22 44 42 21 39]
 [17 43 23 20 30]
 [12 11 31 46 40]
 [46 47 42 37 23]
 [49 43 46 50 34]]
Center Sub-array (3, 3):
 [[43 23 20]
 [11 31 46]
 [47 42 37]]
Modified Sub-array (3, 3):
 [[33 13 10]
 [ 1 21 36]
 [37 32 27]]
